using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MatricesOneOperationThousandsOfChangesExample
{
    /// <summary>
    /// This class generates a collection of employees with randomized data.
    /// </summary>
    public class EmployeeGenerator
    {
        Random random;

        /// <summary>
        /// Collection of US states for random assignment.
        /// </summary>
        static readonly string[] States = { "CA", "NY", "TX" };

        /// <summary>
        /// A collection of first names for random name generation.
        /// </summary>
        static readonly string[] FirstNames = { "John", "Jane", "Alex", "Emily", "Michael", "Sarah", "David", "Laura" };

        /// <summary>
        /// A collection of last names for random name generation.
        /// </summary>
        static readonly string[] LastNames = { "Smith", "Johnson", "Brown", "Taylor", "Anderson", "Thomas", "Jackson", "White" };

        public EmployeeGenerator(int seed)
        {
            random = new Random(seed);
        }

        /// <summary>
        /// Generates a list of randomized employees.
        /// </summary>
        /// <param name="count"> How many employees we want to generate.</param>
        /// <returns> A list of randomly generated employees.</returns>
        public List<Employee> GetEmployees(int count)
        {
            List<Employee> employees = new List<Employee>();
            

            for (int x = 0; x < count; x++)
            {
                int income = random.Next(4, 50) * 10_000;
                string state = States[random.Next() % States.Length];
                string name = GetRandomName();
                employees.Add(new Employee(x, name, state, income));
            }

            return employees;
        }

        /// <summary>
        /// Generates a random name by combining a random first name and last name.
        /// </summary>
        /// <returns> A random name generated by combinging first and last names.</returns>
        private string GetRandomName()
        {
            string firstName = FirstNames[random.Next() % FirstNames.Length];
            string lastName = LastNames[random.Next() % LastNames.Length];
            return $"{firstName} {lastName}";
        }
    }
}
